version: 2

aliases:
  - &init-host-tags
    name: Init Host Tags
    command: echo "" > .host-tags
  - &debug-info
    name: Debug Info
    command: ./.circleci/debug-info.sh
  - &run-sync
    name: Run Sync
    command: ./bin/dot-sync
  - &run-setup
    name: Run Setup
    command: ./bin/dot-setup

defaults: &defaults
  working_directory: ~/dotfiles
  environment:
    TERM: dumb

jobs:
  setup-ubuntu-18.04:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run: *init-host-tags
      - run: *debug-info
      - run: *run-sync
      - run: *run-setup

  setup-ubuntu-20.04:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - run: *init-host-tags
      - run: *debug-info
      - run: *run-sync
      - run: *run-setup

workflows:
  version: 2
  test:
    jobs:
      - setup-ubuntu-18.04
      - setup-ubuntu-20.04
