version: 2

aliases:
  - &debug-info
    name: Debug Info
    command: ./.circleci/debug-info.sh
  - &run-sync
    name: Run Sync
    command: ./bin/dot-sync personal
  - &run-setup
    name: Run Setup
    command: ./bin/dot-setup

defaults: &defaults
  working_directory: ~/dotfiles

jobs:
  setup-ubuntu-18.04:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run: *debug-info
      - run: *run-sync
      - run: *run-setup

  setup-ubuntu-19.04:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:disco
    steps:
      - checkout
      - run: *debug-info
      - run: *run-sync
      - run: *run-setup

workflows:
  version: 2
  test:
    jobs:
      - setup-ubuntu-18.04
      - setup-ubuntu-19.04
