version: 2

defaults: &defaults
  working_directory: ~/dotfiles

jobs:
  setup-ubuntu-18.04:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Run sync
          command: bash ./bin/dot-sync personal
      - run:
          name: Run setup
          command: bash ./bin/dot-setup

workflows:
  version: 2
  test:
    jobs:
      - setup-ubuntu-18.04
